In [1]:
import numpy as np

In [2]:
#1 Генерация случайной матрицы
A = np.random.normal(1,10,(1000,50))
print(A)

[[  5.7775359   -7.20638762  -3.49025707 ...,  -4.12449329  -0.86374489
    2.57154887]
 [ 19.25111076 -14.19917197   2.65901923 ...,  -4.38435729  15.49253853
   -2.17362392]
 [  1.2219668  -15.12393667   3.61276685 ...,  -9.01958501   5.23471959
   -4.35700754]
 ..., 
 [ 20.51978237   8.78172243   6.41859554 ...,   1.17280862   2.42770028
   10.17525663]
 [ 12.23260072  13.04916023  -3.02230569 ...,  -4.81170722  -1.14890416
   -0.49972206]
 [ -1.52457302 -20.226392    -3.92862988 ..., -14.04094562   5.5422165
   11.93230866]]


In [3]:
#2 Нормировка матрицы
mean_vect = A.mean(axis = 0)
std_vect = A.std(axis = 0)
A_norm = (A - mean_vect)/std_vect
print(A_norm)

[[ 0.46354701 -0.87613411 -0.43951125 ..., -0.50016919 -0.1859723
   0.18120769]
 [ 1.81050167 -1.59235966  0.15872443 ..., -0.52618723  1.48988957
  -0.28239469]
 [ 0.0081263  -1.68707732  0.25151028 ..., -0.99027443  0.43887528
  -0.49571081]
 ..., 
 [ 1.9373309   0.76142432  0.52447685 ...,  0.03020605  0.15126858
   0.92408833]
 [ 1.1088605   1.1985103  -0.39398635 ..., -0.56897426 -0.21518967
  -0.11885483]
 [-0.26644557 -2.20968873 -0.48215859 ..., -1.49302193  0.47038136
   1.09575194]]


In [4]:
#3 Операции над элементами матрицы
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])
sum_vect = Z.sum(axis = 1)
print(np.nonzero(sum_vect < 10))

(array([0, 2, 3], dtype=int64),)


In [5]:
#4 Объединение матриц
E_1 = np.eye(3)
E_2 = np.eye(3)
X = np.vstack((E_1, E_2))
print(X)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
